var dt_static2 = "http://www.mxiaotu.com/";
document.writeln("<footer class=\'footer \'>");
document.writeln("");
document.writeln("    <ul class=\'am-container-1\'>");
document.writeln("");
document.writeln("        <li class=\'am-u-lg-4 am-u-md-4 am-u-sm-12 part-5-li2\'>");
document.writeln("            <div class=\'part-5-title\'>联系我们</div>");
document.writeln("            <div class=\'part-5-words2\'>");
document.writeln("                <span>地址:北京市朝阳区建国路15号华文国际传媒大厦C座</span>");
document.writeln("                <span>电话:010-65708561</span>");
document.writeln("                <span>邮箱:service@kexuemihe.com</span>");
//document.writeln("                <span><i class=\'am-icon-phone\'></i><em>010-65708561</em></span>");
document.writeln("            </div>");
document.writeln("        </li>");
document.writeln("        <li class=\'am-u-lg-4 am-u-md-4 am-u-sm-12 \'>");
document.writeln("            <div class=\'part-5-title\'>相关链接</div>");
document.writeln("            <div class=\'part-5-words2\'>");
document.writeln("                <ul class=\'part-5-words2-ul\'>");
document.writeln("                    <li class=\'am-u-lg-4 am-u-md-6 am-u-sm-4\'><a href=\'"+dt_static2+"lesson.html\'>课程理念</a></li>");
document.writeln("                    <li class=\'am-u-lg-4 am-u-md-6 am-u-sm-4\'><a href='"+dt_static2+"lesson-show.html\'>课程体系</a></li>");
document.writeln("                    <li class=\'am-u-lg-4 am-u-md-6 am-u-sm-4\'><a href='"+dt_static2+"http://www.mxiaotu.com/news/list.php?catid=50\'>趣味视频</a></li>");
document.writeln("                    <li class=\'am-u-lg-4 am-u-md-6 am-u-sm-4\'><a href=\'"+dt_static2+"http://www.mxiaotu.com/news/list.php?catid=5\'>新闻动态</a></li>");
document.writeln("                    <li class=\'am-u-lg-4 am-u-md-6 am-u-sm-4\'><a href=\'"+dt_static2+"cooperat.html\'>合作共赢</a></li>");
document.writeln("                    <li class=\'am-u-lg-4 am-u-md-6 am-u-sm-4\'><a href=\'"+dt_static2+"about-us.html\'>联系我们</a></li>");
document.writeln("                    <div class=\'clear\'></div>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("        </li>");
document.writeln("        <li class=\'am-u-lg-4 am-u-md-4 am-u-sm-12 \'>");
document.writeln("            <div class=\'part-5-title\'>微信公众号</div>");
document.writeln("            <img class=\'erweima\' src=\'"+dt_static2+"resource/img/erweima.png\' alt=\'\'/>");
document.writeln("        </li>");
document.writeln("        <div class=\'clear\'></div>");
document.writeln("    </ul>");
document.writeln("");
document.writeln("</footer>");
document.writeln("<div style=\'text-align: center;background-color: #151515;padding: 3px;color: #8e8e8e;font-size: 14px\' >");
document.writeln("    <p>©2012-2017 北京芈小兔教育科技有限公司&nbsp;&nbsp;&nbsp;&nbsp;网站备案：京ICP备17069440号-1</p>");
document.writeln("</div>");/**
 * Created by a on 2019-04-29.
 */
